### ISSUE TITLE
Consider migrating to newer `navigator.mediaDevices`

### ISSUE THREAD

**Issue by saschanaz** [hyunjun529/WebTalkingVRoid#1]
https://github.com/hyunjun529/WebTalkingVRoid/blob/b5c14f0af55ed6dbc639aec7abc14659be6f1a82/script/audio.js#L11-L30

Currently audio.js uses the legacy `navigator.getUserMedia()` API with callbacks, but consider migrating to the newer `navigator.mediaDevices.getUserMedia()`, which is based on Promise and supported by Firefox without `moz` prefix.

**Comment by hyunjun529** [comment]
There are the MDN web docs about [MediaDevices/getUserMedia](https://developer.mozilla.org/ko/docs/Web/API/MediaDevices/getUserMedia) I refer to.

And I changed code to use Promise and newer API on commit 35f87a4.

**Comment by saschanaz** [comment]
Confirming that now the audio works on Firefox (although the sound is somehow not smooth with unknown reason) 👍
