### ISSUE TITLE
Warning: `new AudioContext()` was not allowed to start

### ISSUE THREAD

**Issue by saschanaz** [hyunjun529/WebTalkingVRoid#2]
![image](https://user-images.githubusercontent.com/3396686/52321716-7232ed80-2a19-11e9-9d7b-6b5c57311a36.png)

Full message:

>audio.js:6 The AudioContext was not allowed to start. It must be resumed (or created) after a user gesture on the page. https://goo.gl/7K7WLu

This blocks recording/playing even after the microphone access permission is given.

Current workaround: Refresh and click anywhere before page loading ends 🤣

**Comment by hyunjun529** [comment]
Thanks for your reporting @saschanaz! Threre are fixed commit 3ffd637.
It seems to scope problem, and I changed the scope to create AudioContext when click the start button.

Sorry to say that I don't have test code, but I didn't find same Warning after that commit in my devices.

**Comment by saschanaz** [comment]
Thanks, it now works on my machine 👍
